name: Executar ETL Periodicamente

# Define quando o workflow será executado
on:
  schedule:
    - cron: '50 19 * * *'  # Executa diariamente à meia-noite UTC
  workflow_dispatch:    # Permite execução manual

jobs:
  executar_etl:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do repositório
      - name: Checkout do código
        uses: actions/checkout@v3

      # Passo 2: Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Especifique a versão do Python que você está usando

      # Passo 3: Instalar dependências
      - name: Instalar dependências
        
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Executar o script ETL
      - name: Executar script ETL
        run: |
          python etl-exe.py
