name: Deploy Consultas no CRM to Digital Ocean

# on -> Define quando o workflow será acionado (neste caso, a cada push na branch main ou manualmente)
on:
  # Define
  push:
    branches:
      - main
  # Permite que o workflow seja executado manualmente
  workflow_dispatch:

# jobs -> Cada job define um conjunto de ações que o workflow vai realizar
jobs:
  deploy:
    # Define o ambiente que o job será executado (neste caso, a versão mais recente do ubuntu)
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do repositório (permite que o workflow acesse os arquivos do projeto)
      - name: Check out the repository
        uses: actions/checkout@v3

      # Passo 2: Adiciona a chave privada do droplet da Digital Ocean
      - name: Add SSH Key
        # A primeira linha cria um arquivo .pem a partir da Secret do GitHub
        # chmod 600 ~/droplet-do-key.pem -> Dá permissão de leitura e escrita ao proprietário do arquivo (quem gerou a chave)
        run: |
          echo "${{ secrets.DROPLET_DO_SSH_KEY }}" > ~/droplet-do-key.pem
          chmod 600 ~/droplet-do-key.pem

      # Passo 3: Faz o deploy no droplet da Digital Ocean
      - name: Deploy to Digital Ocean Droplet
        # A primeira linha é para conectar ao droplet da Digital Ocean
        # << EOF -> (End of File) Indica que os comandos que foram passados até o momento do '<< EOF' são um bloco
        # cd ~/app -> Navega para o diretório do projeto
        # source venv-crm/bin/activate -> Ativar o ambiente virtual
        # git pull origin main -> Faz o 'git pull' para pegar as últimas mudanças
        # killall gunicorn -> Interrompe todos os processos em andamento
        # nohup gunicorn --bind 0.0.0.0:3333 back:app > gunicorn.log 2>&1 &
        #   nohup -> Permite que o processo seja executado em segundo plano, mesmo após o encerramento da sessão SSH. Ele ignora o hangup quando a sessão termina
        #   gunicorn -> Inicia um servidor WSGI
        #   --bind 0.0.0.0:3333 -> Faz o servidor ouvir em todas as interfaces de rede (0.0.0.0) na porta 3333
        #   back:app -> É o caminho para o módulo da aplicação. 'back' se refere ao arquivo 'back.py', 'app' se refere à variável 'app' dentro do arquivo, que representa a instância do Flask
        #   > gunicorn.log 2>&1 -> Redireciona a saída padrão (stdout) e a saída de erro (stderr) para o arquivo gunicorn.log
        #   & -> Libera o terminal de ficar 'preso' esperando o gunicorn terminar, permitindo que outros comandos sejam executados e/ou que o GitHub Actions seja encerrado
        # EOF -> (End of File) Finaliza o bloco de comandos, indicando que não há mais comandos para serem lidos
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/droplet-do-key.pem ${{ secrets.DROPLET_IP_AND_USER }} << EOF
          cd ~/app
          source venv/bin/activate
          git pull origin main
          killall gunicorn || echo "No gunicorn process found."
          nohup gunicorn --bind 0.0.0.0:3333 back:app > gunicorn.log 2>&1 &
          EOF
