ROUTE='http://146.190.147.250:3333/ask'
SHEETS_ID='18Ub6-90lW3CXIpezs2Sjrtx5tlnRhMBaUEY_Jz30hHg'

[google_service_account]
type = "service_account"
project_id = "automacao-comershow"
private_key_id = "028dde09985355a9321889242c5146bf7c827eaf"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDUS6rVuid8EcOc
9mJ4Z3JJ0SZRL3TFnCZxePdUX9uE1P7L6aE77EY3/5g83WygYyXT8CnqnR/wOIPK
r5uzlu6OyPCADSXKiiJi1Op1rjCzjU34CmWkAohWmnoXzRgTLv5pnC8qzbP+/IsF
a5azMIz9ZrajgGGBQPVDlWWasQvKa5rT25zy8Moto3ZKnrywBsdco58r6kOdGKk5
ICOGYYmQZSYwavDalXPfcl8Q+Sfh6wTbPmOnhGeFYiVjgb5SLGqTVQUebAkNX/pC
t7mWSVrJ7t0djT1oKyRpf2CHavkX00yuRt/Yb/C1rIhfCmLgjftcjcLOUW7t8q78
btBiohtfAgMBAAECggEAZHywj1v/BpYt/mUNdSqaCWDLf1A0OLlR5RI6GCELelOL
i5+5pvCOyEDeoai5my1zIV+jp57aGE3X7B+1VouRvdpVJHeUtMsvvZJErJFYEhVH
m6noNHrSaBPUyOFWjPYIjJrWJK+bjI2jjFxBx+2qPuPYfYnuHU1PCr9ziYZWK2ho
up31EYuW7wbtvmqGmzfwZ6Q67IwF2WYTV4GGErkT3hRL039Ix8YwVqKUUYbrMWgB
yYkNUQbA4CzLntnGNjJCs7nbSsERG/M9RD9MfznykU2F2I/cZjcCFhlDCGB7/26E
BN1rTGlxbJ9+k7HOtD1hA/tNFXfEN5naLZLnEwyViQKBgQD0wD2eD/NSRo2zaBxY
n/+5hF2g3cets+3SZNgLW9KdRTZE4XXJVjNoOoXxxoRayj3s1tkXlUcO+KgJ/Yaj
X7JWNwuNsjFrBb3ue5fobWB43UdUN6byZkBOhsZs6JbZh7/MakQJ/v1LeBBud5gk
kvcv41Furh9tWLOd2rd/evDSFQKBgQDeDY3fdyISiE51KP/vgbvgjOoyShVlFfAI
wHwrxadvrhZyADHys2flQ3AQAQYWmDcMgCBZVRNqd2fB3KgNRefOJgfVnIk3Ce68
BZt7guQZCEqNiyIOx8I/UYA04C8WVDd8gfVy0Bd3Gbyn0gDPUK7bX4Sxq2H/NiTu
44AAqqj4owKBgQDfw0ZSVUjjRsfUZ3HLAPTemoqzQTCGucLLoRD4SYnj6Vw1W1/B
pEK5nw/IvPNSwiYde0vdSMg/gsy23YgTo7E7K3YvpOOTcht0hqCaii0yMzQ8ZekH
Ir7WTFfrSDZqSLbs35a3AN54+hsjs8lwXsEJki1oIF9xLDCDOGydazvzBQKBgQDJ
Ax4eYBtBCZF0r/PYHeo04XuUoMnzY0OSuKTvfxMOn1qEQrb0jQINYdoNMtAPHiYf
M9GU7NYRuBv+O8EJmvG4BWdsMTNp1pz+KllRGvFf08ihj4T6Ok0WwrG7rAIURZKh
LIhEMio7z9mfVhUTl2djAXn+2DVzMdGHS/zxHYyu3wKBgQCbiZuANIgl1ASq4hXT
b6LtBCH4AtytU32sewWdfE6R3FSpojBKnlLeAkPiTxFNWDzsjJ4nzkj2GjeaK3cM
+Ra1QMh98EWbPiu5DYchyRyneA9w50LykIIsuNJ0TWUoNJ2zze+IFs6elEv+dZPy
sG/cdsUyW0WOwwwLBEdcuW0H+Q==
-----END PRIVATE KEY-----'''
client_email = "integracaopipesheets@automacao-comershow.iam.gserviceaccount.com"
client_id = "103157146497382105731"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/integracaopipesheets%40automacao-comershow.iam.gserviceaccount.com"
